export const subLocs = {
  parent: {
    center: { lon: 44.787526, lat: 41.708692 },
    osm_id: "1",
    parent_osm_id: 0,
    name: { ka: "თბილისი", en: "Tbilisi", ru: "Тбилиси" },
    IsCapital: true,
  },
  subLocs: [
    {
      center: { lon: 44.825635, lat: 41.758395 },
      osm_id: 1,
      type: "district",
      parent_osm_id: "1",
      name: {
        ka: "გლდანი-ნაძალადევი",
        en: "Gldani-Nadzaladevi",
        ru: "Глдани-Надзаладеви",
      },
      pathway: {
        ka: "გლდანი-ნაძალადევი",
        en: "Gldani-Nadzaladevi",
        ru: "Глдани-Надзаладеви",
      },
      seo_title: {
        ka: "გლდანი-ნაძალადევში",
        en: "In Gldani-Nadzaladevi",
        ru: "В Глдани-Надзаладеви",
      },
      childs: [
        {
          osm_id: 1,
          parent_osm_id: 1,
          type: "urban",
          name: { ka: "ავჭალა", en: "Avchala", ru: "Авчала" },
          pathway: { ka: "ავჭალა", en: "Avchala", ru: "Авчала" },
          seo_title: { ka: "ავჭალაში", en: "In Avchala", ru: "В Авчала" },
          has_street: true,
          streets_count: 36,
          subs: 36,
        },
        {
          osm_id: 2,
          parent_osm_id: 1,
          type: "urban",
          name: { ka: "გლდანი", en: "Gldani", ru: "Глдани" },
          pathway: { ka: "გლდანი", en: "Gldani", ru: "Глдани" },
          seo_title: { ka: "გლდანში", en: "In Gldani", ru: "В Глдани" },
          has_street: true,
          streets_count: 64,
          subs: 64,
        },
        {
          osm_id: 3,
          parent_osm_id: 1,
          type: "urban",
          name: { ka: "გლდანულა", en: "Gldanula", ru: "Глданула" },
          pathway: { ka: "გლდანულა", en: "Gldanula", ru: "Глданула" },
          seo_title: { ka: "გლდანულაში", en: "In Gldanula", ru: "В Глданула" },
          has_street: true,
          streets_count: 5,
          subs: 5,
        },
        {
          osm_id: 4,
          parent_osm_id: 1,
          type: "urban",
          name: { ka: "ზაჰესი", en: "Zahesi", ru: "Загеси" },
          pathway: { ka: "ზაჰესი", en: "Zahesi", ru: "Загеси" },
          seo_title: { ka: "ზაჰესში", en: "In Zahesi", ru: "В Загеси" },
          has_street: true,
          streets_count: 15,
          subs: 15,
        },
        {
          osm_id: 5,
          parent_osm_id: 1,
          type: "urban",
          name: {
            ka: "თბილისის ზღვა",
            en: "Tbilisisea",
            ru: "Тбилисское море",
          },
          pathway: {
            ka: "თბილისის ზღვა",
            en: "Tbilisi sea",
            ru: "Тбилисскоеморе",
          },
          seo_title: {
            ka: "თბილისის ზღვაზე",
            en: "In  Tbilisi sea",
            ru: "В Тбилисское море",
          },
          has_street: true,
          streets_count: 19,
          subs: 19,
        },
        {
          osm_id: 6,
          parent_osm_id: 1,
          type: "urban",
          name: { ka: "თემქა", en: "Temqa", ru: "ТЭВЗ" },
          pathway: { ka: "თემქა", en: "Temqa", ru: "ТЭВЗ" },
          seo_title: { ka: "თემქაზე", en: "In Temqa", ru: "В ТЭВЗ" },
          has_street: true,
          streets_count: 38,
          subs: 38,
        },
        {
          osm_id: 7,
          parent_osm_id: 1,
          type: "urban",
          name: {
            ka: "კონიაკის დას.",
            en: "Koniaki village",
            ru: "пос.Кониаки",
          },
          pathway: {
            ka: "კონიაკის დას.",
            en: "Koniaki village",
            ru: "пос. Кониаки",
          },
          seo_title: {
            ka: "კონაკისდას.-ში",
            en: "In  Koniaki village",
            ru: "В пос. Кониаки",
          },
          has_street: true,
          streets_count: 2,
          subs: 2,
        },
        {
          osm_id: 8,
          parent_osm_id: 1,
          type: "urban",
          name: { ka: "ლოტკინი", en: "Lotkini", ru: "Лоткини" },
          pathway: { ka: "ლოტკინი", en: "Lotkini", ru: "Лоткини" },
          seo_title: { ka: "ლოტკინზე", en: "In Lotkini", ru: "В Лоткини" },
          has_street: true,
          streets_count: 59,
          subs: 59,
        },
        {
          osm_id: 9,
          parent_osm_id: 1,
          type: "urban",
          name: { ka: "მუხიანი", en: "Mukhiani", ru: "Мухиани" },
          pathway: { ka: "მუხიანი", en: "Mukhiani", ru: "Мухиани" },
          seo_title: { ka: "მუხიანში", en: "In Mukhiani", ru: "В Мухиани" },
          has_street: true,
          streets_count: 86,
          subs: 86,
        },
        {
          osm_id: 10,
          parent_osm_id: 1,
          type: "urban",
          name: { ka: "ნაძალადევი", en: "Nadzaladevi", ru: "Надзаладеви" },
          pathway: { ka: "ნაძალადევი", en: "Nadzaladevi", ru: "Надзаладеви" },
          seo_title: {
            ka: "ნაძალადევში",
            en: "In Nadzaladevi",
            ru: "В Надзаладеви",
          },
          has_street: true,
          streets_count: 75,
          subs: 75,
        },
        {
          osm_id: 11,
          parent_osm_id: 1,
          type: "urban",
          name: { ka: "სან. ზონა", en: "Sanzona", ru: "Сан.Зона" },
          pathway: { ka: "სან. ზონა", en: "Sanzona", ru: "Сан. Зона" },
          seo_title: { ka: "სან. ზონაში", en: "In  Sanzona", ru: "ВСан. Зона" },
          has_street: true,
          streets_count: 46,
          subs: 46,
        },
        {
          osm_id: 12,
          parent_osm_id: 1,
          type: "urban",
          name: { ka: "სოფ. გლდანი", en: "Gldani village", ru: "селоГлдани" },
          pathway: {
            ka: "სოფ. გლდანი",
            en: "Gldani village",
            ru: "село Глдани",
          },
          seo_title: {
            ka: "სოფ. გლდანში",
            en: "In Gldani village",
            ru: "В село Глдани",
          },
          has_street: true,
          streets_count: 8,
          subs: 8,
        },
      ],
      streets_count: 0,
      subs: 12,
    },
    {
      center: { lon: 44.645734, lat: 41.673312 },
      osm_id: 2,
      type: "district",
      parent_osm_id: "1",
      name: {
        en: "Suburbsof Tbilisi",
        ka: "თბილისის შემოგარენი",
        ru: "Пригород Тбилиси",
      },
      pathway: {
        en: "Suburbsof Tbilisi",
        ka: "თბილისის შემოგარენი",
        ru: "Пригород Тбилиси",
      },
      seo_title: {
        en: "In Suburbs of Tbilisi",
        ka: "თბილისის შემოგარენში",
        ru: "В Пригород Тбилиси",
      },
      childs: [
        {
          osm_id: 118,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "კვესეთი", en: "Kveseti", ru: "Квесети" },
          pathway: { ka: "კვესეთი", en: "Kveseti", ru: "Квесети" },
          seo_title: { ka: "კვესეთში", en: "in Kveseti", ru: "в Квесети" },
          has_street: true,
          streets_count: 1,
          subs: 1,
        },
        {
          osm_id: 13,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "ახალდაბა", en: "Akhaldaba", ru: "Ахалдаба" },
          pathway: { ka: "ახალდაბა", en: "Akhaldaba", ru: "Ахалдаба" },
          seo_title: { ka: "ახალდაბაში", en: "In Akhaldaba", ru: "В Ахалдаба" },
          has_street: false,
          streets_count: 0,
          subs: 0,
        },
        {
          osm_id: 14,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "ბეთანია", en: "Betania", ru: "Бетания" },
          pathway: { ka: "ბეთანია", en: "Betania", ru: "Бетания" },
          seo_title: { ka: "ბეთანიაში", en: "In Betania", ru: "В Бетания" },
          has_street: true,
          streets_count: 1,
          subs: 1,
        },
        {
          osm_id: 15,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "კაკლები", en: "Kaklebi", ru: "Каклеби" },
          pathway: { ka: "კაკლები", en: "Kaklebi", ru: "Каклеби" },
          seo_title: { ka: "კაკლებში", en: "In Kaklebi", ru: "В Каклеби" },
          has_street: true,
          streets_count: 1,
          subs: 1,
        },
        {
          osm_id: 16,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "კიკეთი", en: "Kiketi", ru: "Кикети" },
          pathway: { ka: "კიკეთი", en: "Kiketi", ru: "Кикети" },
          seo_title: { ka: "კიკეთში", en: "In Kiketi", ru: "В Кикети" },
          has_street: true,
          streets_count: 18,
          subs: 18,
        },
        {
          osm_id: 17,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "კოჯორი", en: "Kojori", ru: "Коджори" },
          pathway: { ka: "კოჯორი", en: "Kojori", ru: "Коджори" },
          seo_title: { ka: "კოჯორში", en: "In Kojori", ru: "В Коджори" },
          has_street: true,
          streets_count: 6,
          subs: 6,
        },
        {
          osm_id: 18,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "ოქროყანა", en: "Oqrokana", ru: "Окрокана" },
          pathway: { ka: "ოქროყანა", en: "Oqrokana", ru: "Окрокана" },
          seo_title: { ka: "ოქროყანაში", en: "In Oqrokana", ru: "В Окрокана" },
          has_street: true,
          streets_count: 6,
          subs: 6,
        },
        {
          osm_id: 19,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "ტაბახმელა", en: "Tabakhmela", ru: "Табахмела" },
          pathway: { ka: "ტაბახმელა", en: "Tabakhmela", ru: "Табахмела" },
          seo_title: {
            ka: "ტაბახმელაში",
            en: "In Tabakhmela",
            ru: "В Табахмела",
          },
          has_street: true,
          streets_count: 11,
          subs: 11,
        },
        {
          osm_id: 20,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "შინდისი", en: "Shindisi", ru: "Шиндиси" },
          pathway: { ka: "შინდისი", en: "Shindisi", ru: "Шиндиси" },
          seo_title: { ka: "შინდისში", en: "In Shindisi", ru: "В Шиндиси" },
          has_street: true,
          streets_count: 16,
          subs: 16,
        },
        {
          osm_id: 21,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "წავკისი", en: "Tsavkisi", ru: "Цавкиси" },
          pathway: { ka: "წავკისი", en: "Tsavkisi", ru: "Цавкиси" },
          seo_title: { ka: "წავკისში", en: "In Tsavkisi", ru: "В Цавкиси" },
          has_street: true,
          streets_count: 5,
          subs: 5,
        },
        {
          osm_id: 22,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "წყნეთი", en: "Tskneti", ru: "Цкнети" },
          pathway: { ka: "წყნეთი", en: "Tskneti", ru: "Цкнети" },
          seo_title: { ka: "წყნეთში", en: "In Tskneti", ru: "В Цкнети" },
          has_street: true,
          streets_count: 40,
          subs: 40,
        },
        {
          osm_id: 68,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "წვერი", en: "Tsveri", ru: "Цвери" },
          pathway: { ka: "წვერი", en: "Tsveri", ru: "Цвери" },
          seo_title: { ka: "წვერში", en: "In Tsveri", ru: "В Цвери" },
          has_street: false,
          streets_count: 0,
          subs: 0,
        },
        {
          osm_id: 69,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "მსხალდიდი", en: "Mskhaldidi", ru: "Мсхалдиди" },
          pathway: { ka: "მსხალდიდი", en: "Mskhaldidi", ru: "Мсхалдиди" },
          seo_title: {
            ka: "მსხალდიდაში",
            en: "In Mskhaldidi",
            ru: "В Мсхалдиди",
          },
          has_street: false,
          streets_count: 0,
          subs: 0,
        },
        {
          osm_id: 70,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "წოდორეთი", en: "Tsodoreti", ru: "Цодорети" },
          pathway: { ka: "წოდორეთი", en: "Tsodoreti", ru: "Цодорети" },
          seo_title: { ka: "წოდორეთში", en: "In Tsodoreti", ru: "В Цодорети" },
          has_street: true,
          streets_count: 1,
          subs: 1,
        },
        {
          osm_id: 102,
          parent_osm_id: 2,
          type: "urban",
          name: { ka: "ზემო ლისი", en: "Upper Lisi", ru: "ВерхнийЛиси" },
          pathway: { ka: "ზემო ლისი", en: "Upper Lisi", ru: "Верхний Лиси" },
          seo_title: {
            ka: "ზემო ლისზე",
            en: "In Upper Lisi",
            ru: "В Верхний Лиси",
          },
          has_street: true,
          streets_count: 1,
          subs: 1,
        },
      ],
      streets_count: 0,
      subs: 15,
    },
    {
      center: { lon: 44.812074, lat: 41.714843 },
      osm_id: 3,
      type: "district",
      parent_osm_id: "1",
      name: {
        ka: "დიდუბე-ჩუღურეთი",
        en: "Didube-Chugureti",
        ru: "Дидубе-Чугурети",
      },
      pathway: {
        ka: "დიდუბე-ჩუღურეთი",
        en: "Didube-Chugureti",
        ru: "Дидубе-Чугурети",
      },
      seo_title: {
        ka: "დიდუბე-ჩუღურეთში",
        en: "In Didube-Chugureti",
        ru: "В Дидубе-Чугурети",
      },
      childs: [
        {
          osm_id: 103,
          parent_osm_id: 3,
          type: "urban",
          name: { ka: "ივერთუბანი", en: "Ivertuban", ru: "Ивертубан" },
          pathway: { ka: "ივერთუბანი", en: "Ivertuban", ru: "Ивертубан" },
          seo_title: {
            ka: "ივერთუბანი",
            en: "In Ivertuban",
            ru: "В Ивертубан",
          },
          has_street: true,
          streets_count: 1,
          subs: 1,
        },
        {
          osm_id: 23,
          parent_osm_id: 3,
          type: "urban",
          name: { ka: "დიდუბე", en: "Didube", ru: "Дидубе" },
          pathway: { ka: "დიდუბე", en: "Didube", ru: "Дидубе" },
          seo_title: { ka: "დიდუბეში", en: "In Didube", ru: "В Дидубе" },
          has_street: true,
          streets_count: 44,
          subs: 44,
        },
        {
          osm_id: 24,
          parent_osm_id: 3,
          type: "urban",
          name: { ka: "დიღმის მასივი", en: "Digomi", ru: "Дигоми" },
          pathway: { ka: "დიღმისმასივი", en: "Digomi", ru: "Дигоми" },
          seo_title: { ka: "დიღმის მასივში", en: "In  Digomi", ru: "В Дигоми" },
          has_street: true,
          streets_count: 28,
          subs: 28,
        },
        {
          osm_id: 25,
          parent_osm_id: 3,
          type: "urban",
          name: { ka: "კუკია", en: "Kukia", ru: "Кукия" },
          pathway: { ka: "კუკია", en: "Kukia", ru: "Кукия" },
          seo_title: { ka: "კუკიაზე", en: "In Kukia", ru: "В Кукия" },
          has_street: true,
          streets_count: 54,
          subs: 54,
        },
        {
          osm_id: 26,
          parent_osm_id: 3,
          type: "urban",
          name: {
            ka: "სვანეთის უბანი",
            en: "Svanetisubani",
            ru: "Сванетис убани",
          },
          pathway: {
            ka: "სვანეთის უბანი",
            en: "Svanetis ubani",
            ru: "Сванетисубани",
          },
          seo_title: {
            ka: "სვანეთის უბანში",
            en: "In  Svanetis ubani",
            ru: "В Сванетис убани",
          },
          has_street: true,
          streets_count: 21,
          subs: 21,
        },
        {
          osm_id: 27,
          parent_osm_id: 3,
          type: "urban",
          name: { ka: "ჩუღურეთი", en: "Chugureti", ru: "Чугурети" },
          pathway: { ka: "ჩუღურეთი", en: "Chugureti", ru: "Чугурети" },
          seo_title: { ka: "ჩუღურეთში", en: "In Chugureti", ru: "В Чугурети" },
          has_street: true,
          streets_count: 97,
          subs: 97,
        },
      ],
      streets_count: 0,
      subs: 6,
    },
    {
      center: { lon: 44.741006, lat: 41.76595 },
      osm_id: 4,
      type: "district",
      parent_osm_id: "1",
      name: {
        ka: "ვაკე-საბურთალო",
        en: "Vake-Saburtalo",
        ru: "Ваке-Сабуртало",
      },
      pathway: {
        ka: "ვაკე-საბურთალო",
        en: "Vake-Saburtalo",
        ru: "Ваке-Сабуртало",
      },
      seo_title: {
        ka: "ვაკე-საბურთალოში",
        en: "In Vake-Saburtalo",
        ru: "В Ваке-Сабуртало",
      },
      childs: [
        {
          osm_id: 106,
          parent_osm_id: 4,
          type: "urban",
          name: { ka: "დიღმის ჭალა", en: "DighomiTchala", ru: "Дигоми тчала" },
          pathway: {
            ka: "დიღმის ჭალა",
            en: "Dighomi Tchala",
            ru: "Дигоми тчала",
          },
          seo_title: {
            ka: "დიღმისჭალაზე",
            en: "In  Dighomi Tchala",
            ru: "Дигоми тчала",
          },
          has_street: true,
          streets_count: 1,
          subs: 1,
        },
        {
          osm_id: 111,
          parent_osm_id: 4,
          type: "urban",
          name: { ka: "ქოშიგორა", en: "Koshigora", ru: "Кошигора" },
          pathway: { ka: "ქოშიგორა", en: "Koshigora", ru: "Кошигора" },
          seo_title: { ka: "ქოშიგორაში", en: "in Koshigora", ru: "В Кошигоре" },
          has_street: true,
          streets_count: 6,
          subs: 6,
        },
        {
          osm_id: 28,
          parent_osm_id: 4,
          type: "urban",
          name: { ka: "ბაგები", en: "Bagebi", ru: "Багеби" },
          pathway: { ka: "ბაგები", en: "Bagebi", ru: "Багеби" },
          seo_title: { ka: "ბაგებში", en: "In Bagebi", ru: "В Багеби" },
          has_street: true,
          streets_count: 4,
          subs: 4,
        },
        {
          osm_id: 29,
          parent_osm_id: 4,
          type: "urban",
          name: { ka: "დიდი დიღომი", en: "Didi digomi", ru: "ДидиДигоми" },
          pathway: { ka: "დიდი დიღომი", en: "Didi digomi", ru: "Диди Дигоми" },
          seo_title: {
            ka: "დიდ დიღომში",
            en: "In Didi digomi",
            ru: "В Диди Дигоми",
          },
          has_street: true,
          streets_count: 93,
          subs: 93,
        },
        {
          osm_id: 30,
          parent_osm_id: 4,
          type: "urban",
          name: { ka: "დიღომი 1-9", en: "Digomi1-9", ru: "Дигоми 1-9" },
          pathway: { ka: "დიღომი 1-9", en: "Digomi 1-9", ru: "Дигоми 1-9" },
          seo_title: {
            ka: "დიღომი 1-9-ში",
            en: "In Digomi 1-9",
            ru: "В Дигоми 1-9",
          },
          has_street: true,
          streets_count: 28,
          subs: 28,
        },
        {
          osm_id: 38,
          parent_osm_id: 4,
          type: "urban",
          name: { en: "Vake", ka: "ვაკე", ru: "Ваке" },
          pathway: { en: "Vake", ka: "ვაკე", ru: "Ваке" },
          seo_title: { en: "In Vake", ka: "ვაკეში", ru: "В Ваке" },
          has_street: true,
          streets_count: 55,
          subs: 55,
        },
        {
          osm_id: 39,
          parent_osm_id: 4,
          type: "urban",
          name: { ka: "ვაშლიჯვარი", en: "Vashlijvari", ru: "Вашлиджвари" },
          pathway: { ka: "ვაშლიჯვარი", en: "Vashlijvari", ru: "Вашлиджвари" },
          seo_title: {
            ka: "ვაშლიჯვარში",
            en: "In Vashlijvari",
            ru: "В Вашлиджвари",
          },
          has_street: true,
          streets_count: 14,
          subs: 14,
        },
        {
          osm_id: 40,
          parent_osm_id: 4,
          type: "urban",
          name: { ka: "ვეძისი", en: "Vedzisi", ru: "Ведзиси" },
          pathway: { ka: "ვეძისი", en: "Vedzisi", ru: "Ведзиси" },
          seo_title: { ka: "ვეძისში", en: "In Vedzisi", ru: "В Ведзиси" },
          has_street: true,
          streets_count: 27,
          subs: 27,
        },
        {
          osm_id: 41,
          parent_osm_id: 4,
          type: "urban",
          name: { ka: "თხინვალი", en: "Tkhinvali", ru: "Тхинвали" },
          pathway: { ka: "თხინვალი", en: "Tkhinvali", ru: "Тхинвали" },
          seo_title: { ka: "თხინვალში", en: "In Tkhinvali", ru: "В Тхинвали" },
          has_street: true,
          streets_count: 2,
          subs: 2,
        },
        {
          osm_id: 42,
          parent_osm_id: 4,
          type: "urban",
          name: { ka: "კუს ტბა", en: "Turtle lake", ru: "Черепашьеозеро" },
          pathway: { ka: "კუს ტბა", en: "Turtle lake", ru: "Черепашье озеро" },
          seo_title: {
            ka: "კუს ტბაზე",
            en: "In Turtle lake",
            ru: "В Черепашье озеро",
          },
          has_street: false,
          streets_count: 0,
          subs: 0,
        },
        {
          osm_id: 43,
          parent_osm_id: 4,
          type: "urban",
          name: { ka: "ლისი", en: "Lisilake", ru: "Озеро Лиси" },
          pathway: { ka: "ლისი", en: "Lisi lake", ru: "Озеро Лиси" },
          seo_title: { ka: "ლისზე", en: "In Lisi lake", ru: "В Озеро Лиси" },
          has_street: true,
          streets_count: 15,
          subs: 15,
        },
        {
          osm_id: 44,
          parent_osm_id: 4,
          type: "urban",
          name: { ka: "მუხათგვერდი", en: "Mukhatgverdi", ru: "Мухатгверди" },
          pathway: { ka: "მუხათგვერდი", en: "Mukhatgverdi", ru: "Мухатгверди" },
          seo_title: {
            ka: "მუხათგვერდში",
            en: "In Mukhatgverdi",
            ru: "В Мухатгверди",
          },
          has_street: false,
          streets_count: 0,
          subs: 0,
        },
        {
          osm_id: 45,
          parent_osm_id: 4,
          type: "urban",
          name: { ka: "მუხათწყარო", en: "Mukhattskaro", ru: "Мухатцкаро" },
          pathway: { ka: "მუხათწყარო", en: "Mukhattskaro", ru: "Мухатцкаро" },
          seo_title: {
            ka: "მუხათწყაროში",
            en: "In Mukhattskaro",
            ru: "В Мухатцкаро",
          },
          has_street: true,
          streets_count: 1,
          subs: 1,
        },
        {
          osm_id: 46,
          parent_osm_id: 4,
          type: "urban",
          name: {
            ka: "ნუცუბიძისფერდობი",
            en: "Nutsubidze plateau",
            ru: "Плато Нуцебидзе",
          },
          pathway: {
            ka: "ნუცუბიძის ფერდობი",
            en: "Nutsubidzeplateau",
            ru: "Плато Нуцебидзе",
          },
          seo_title: {
            ka: "ნუცუბიძის ფერდობზე",
            en: "In  Nutsubidze plateau",
            ru: "ВПлато Нуцебидзе",
          },
          has_street: true,
          streets_count: 18,
          subs: 18,
        },
        {
          osm_id: 47,
          parent_osm_id: 4,
          type: "urban",
          name: { ka: "საბურთალო", en: "Saburtalo", ru: "Сабуртало" },
          pathway: { ka: "საბურთალო", en: "Saburtalo", ru: "Сабуртало" },
          seo_title: {
            ka: "საბურთალოზე",
            en: "In Saburtalo",
            ru: "В Сабуртало",
          },
          has_street: true,
          streets_count: 135,
          subs: 135,
        },
        {
          osm_id: 48,
          parent_osm_id: 4,
          type: "urban",
          name: { ru: "Соф. Дигоми", en: "Sop.Dighomi", ka: "სოფ. დიღომი" },
          pathway: { ru: "Соф. Дигоми", en: "Sop. Dighomi", ka: "სოფ. დიღომი" },
          seo_title: {
            ru: "ВСоф. Дигоми",
            en: "In  Sop. Dighomi",
            ka: "სოფ. დიღომში",
          },
          has_street: true,
          streets_count: 54,
          subs: 54,
        },
        {
          osm_id: 101,
          parent_osm_id: 4,
          type: "urban",
          name: { ka: "ლისისმიმდებარედ", en: "Lisi lake", ru: "Озеро Лиси" },
          pathway: { ka: "ლისის მიმდებარედ", en: "Lisilake", ru: "Озеро Лиси" },
          seo_title: { ka: "ლისთან", en: "In  Lisi lake", ru: "В Озеро Лиси" },
          has_street: true,
          streets_count: 1,
          subs: 1,
        },
      ],
      streets_count: 0,
      subs: 17,
    },
    {
      center: { lon: 44.907861, lat: 41.672671 },
      osm_id: 5,
      type: "district",
      parent_osm_id: "1",
      name: { ka: "ისანი-სამგორი", en: "Isani-Samgori", ru: "Исани-Самгори" },
      pathway: {
        ka: "ისანი-სამგორი",
        en: "Isani-Samgori",
        ru: "Исани-Самгори",
      },
      seo_title: {
        ka: "ისანი-სამგორში",
        en: "In Isani-Samgori",
        ru: "В Исани-Самгори",
      },
      childs: [
        {
          osm_id: 117,
          parent_osm_id: 5,
          type: "urban",
          name: { ka: "აფრიკა", en: "Africa", ru: "Африка" },
          pathway: { ka: "აფრიკა", en: "Africa", ru: "Африка" },
          seo_title: { ka: "აფრიკაში", en: "in Africa", ru: "в Африке" },
          has_street: true,
          streets_count: 2,
          subs: 2,
        },
        {
          osm_id: 49,
          parent_osm_id: 5,
          type: "urban",
          name: {
            ka: "აეროპორტის დას.",
            en: "Airportvillage",
            ru: "пос. Аэропорт",
          },
          pathway: {
            ka: "აეროპორტის დას.",
            en: "Airport village",
            ru: "пос. Аэропорт",
          },
          seo_title: {
            ka: "აეროპორტისდას.-ში",
            en: "In  Airport village",
            ru: "В пос. Аэропорт",
          },
          has_street: true,
          streets_count: 4,
          subs: 4,
        },
        {
          osm_id: 50,
          parent_osm_id: 5,
          type: "urban",
          name: {
            ka: "დამპალოსდას.",
            en: "Dampalo village",
            ru: "пос. Дампало",
          },
          pathway: {
            ka: "დამპალოს დას.",
            en: "Dampalo village",
            ru: "пос.Дампало",
          },
          seo_title: {
            ka: "დამპალოს დას.-ში",
            en: "In  Dampalo village",
            ru: "В пос. Дампало",
          },
          has_street: true,
          streets_count: 1,
          subs: 1,
        },
        {
          osm_id: 51,
          parent_osm_id: 5,
          type: "urban",
          name: { ka: "ვაზისუბანი", en: "Vazisubani", ru: "Вазисубани" },
          pathway: { ka: "ვაზისუბანი", en: "Vazisubani", ru: "Вазисубани" },
          seo_title: {
            ka: "ვაზისუბანში",
            en: "In Vazisubani",
            ru: "В Вазисубани",
          },
          has_street: true,
          streets_count: 25,
          subs: 25,
        },
        {
          osm_id: 52,
          parent_osm_id: 5,
          type: "urban",
          name: { ka: "ვარკეთილი", en: "Varketili", ru: "Варкетили" },
          pathway: { ka: "ვარკეთილი", en: "Varketili", ru: "Варкетили" },
          seo_title: {
            ka: "ვარკეთილში",
            en: "In Varketili",
            ru: "В Варкетили",
          },
          has_street: true,
          streets_count: 54,
          subs: 54,
        },
        {
          osm_id: 53,
          parent_osm_id: 5,
          type: "urban",
          name: { ka: "ისანი", en: "Isani", ru: "Исани" },
          pathway: { ka: "ისანი", en: "Isani", ru: "Исани" },
          seo_title: { ka: "ისანში", en: "In Isani", ru: "В Исани" },
          has_street: true,
          streets_count: 74,
          subs: 74,
        },
        {
          osm_id: 54,
          parent_osm_id: 5,
          type: "urban",
          name: { ka: "ლილო", en: "Lilo", ru: "Лило" },
          pathway: { ka: "ლილო", en: "Lilo", ru: "Лило" },
          seo_title: { ka: "ლილოში", en: "In Lilo", ru: "В Лило" },
          has_street: true,
          streets_count: 33,
          subs: 33,
        },
        {
          osm_id: 55,
          parent_osm_id: 5,
          type: "urban",
          name: {
            ka: "მესამე მასივი",
            en: "Mesame masivi",
            ru: "МесамеМасиви",
          },
          pathway: {
            ka: "მესამე მასივი",
            en: "Mesame masivi",
            ru: "Месаме Масиви",
          },
          seo_title: {
            ka: "მესამემასივში",
            en: "In  Mesame masivi",
            ru: "В Месаме Масиви",
          },
          has_street: true,
          streets_count: 4,
          subs: 4,
        },
        {
          osm_id: 56,
          parent_osm_id: 5,
          type: "urban",
          name: { ka: "ნავთლუღი", en: "Navtlugi", ru: "Навтлуги" },
          pathway: { ka: "ნავთლუღი", en: "Navtlugi", ru: "Навтлуги" },
          seo_title: { ka: "ნავთლუღში", en: "In Navtlugi", ru: "В Навтлуги" },
          has_street: true,
          streets_count: 31,
          subs: 31,
        },
        {
          osm_id: 57,
          parent_osm_id: 5,
          type: "urban",
          name: { ka: "ორთაჭალა", en: "Ortachala", ru: "Ортачала" },
          pathway: { ka: "ორთაჭალა", en: "Ortachala", ru: "Ортачала" },
          seo_title: { ka: "ორთაჭალაში", en: "In Ortachala", ru: "В Ортачала" },
          has_street: true,
          streets_count: 23,
          subs: 23,
        },
        {
          osm_id: 58,
          parent_osm_id: 5,
          type: "urban",
          name: { ka: "ორხევი", en: "Orkhevi", ru: "Орхеви" },
          pathway: { ka: "ორხევი", en: "Orkhevi", ru: "Орхеви" },
          seo_title: { ka: "ორხევში", en: "In Orkhevi", ru: "В Орхеви" },
          has_street: true,
          streets_count: 15,
          subs: 15,
        },
        {
          osm_id: 59,
          parent_osm_id: 5,
          type: "urban",
          name: { ka: "სამგორი", en: "Samgori", ru: "Самгори" },
          pathway: { ka: "სამგორი", en: "Samgori", ru: "Самгори" },
          seo_title: { ka: "სამგორში", en: "In Samgori", ru: "В Самгори" },
          has_street: true,
          streets_count: 35,
          subs: 35,
        },
        {
          osm_id: 60,
          parent_osm_id: 5,
          type: "urban",
          name: { ka: "ფონიჭალა", en: "Ponichala", ru: "Поничала" },
          pathway: { ka: "ფონიჭალა", en: "Ponichala", ru: "Поничала" },
          seo_title: { ka: "ფონიჭალაში", en: "In Ponichala", ru: "В Поничала" },
          has_street: true,
          streets_count: 12,
          subs: 12,
        },
        {
          osm_id: 78,
          parent_osm_id: 5,
          type: "urban",
          name: {
            ka: "მოსკოვის გამზ.",
            en: "MoscowAve.",
            ru: "Московский проспект",
          },
          pathway: {
            ka: "მოსკოვის გამზ.",
            en: "Moscow Ave.",
            ru: "Московскийпроспект",
          },
          seo_title: {
            ka: "მოსკოვის გამზ.-ზე",
            en: "In  Moscow Ave.",
            ru: "В Московскийпроспект",
          },
          has_street: true,
          streets_count: 1,
          subs: 1,
        },
      ],
      streets_count: 0,
      subs: 14,
    },
    {
      center: { lon: 44.799371, lat: 41.692671 },
      osm_id: 6,
      type: "district",
      parent_osm_id: "1",
      name: { ka: "ძველითბილისი", en: "Old Tbilisi", ru: "Старий Тбилиси" },
      pathway: { ka: "ძველი თბილისი", en: "OldTbilisi", ru: "Старий Тбилиси" },
      seo_title: {
        ka: "ძველ თბილისში",
        en: "In  Old Tbilisi",
        ru: "В СтарийТбилиси",
      },
      childs: [
        {
          osm_id: 107,
          parent_osm_id: 6,
          type: "urban",
          name: {
            ka: "წავკისის ველი",
            en: "Tsavkis Valley",
            ru: "Tsavkis Valley",
          },
          pathway: {
            ka: "წავკისისველი",
            en: "Tsavkis Valley",
            ru: "Tsavkis Valley",
          },
          seo_title: {
            ka: "წავკისის ველში",
            en: "Tsavkis Valley",
            ru: "Tsavkis Valley",
          },
          has_street: false,
          streets_count: 0,
          subs: 0,
        },
        {
          osm_id: 61,
          parent_osm_id: 6,
          type: "urban",
          name: { ka: "აბანოთუბანი", en: "Abanotubani", ru: "Абанотубани" },
          pathway: { ka: "აბანოთუბანი", en: "Abanotubani", ru: "Абанотубани" },
          seo_title: {
            ka: "აბანოთუბანში",
            en: "In Abanotubani",
            ru: "В Абанотубани",
          },
          has_street: true,
          streets_count: 40,
          subs: 40,
        },
        {
          osm_id: 62,
          parent_osm_id: 6,
          type: "urban",
          name: { ka: "ავლაბარი", en: "Avlabari", ru: "Авлабари" },
          pathway: { ka: "ავლაბარი", en: "Avlabari", ru: "Авлабари" },
          seo_title: { ka: "ავლაბარში", en: "In Avlabari", ru: "В Авлабари" },
          has_street: true,
          streets_count: 89,
          subs: 89,
        },
        {
          osm_id: 63,
          parent_osm_id: 6,
          type: "urban",
          name: { ka: "ელია", en: "Elia", ru: "Елия" },
          pathway: { ka: "ელია", en: "Elia", ru: "Елия" },
          seo_title: { ka: "ელიაზე", en: "In Elia", ru: "В Елия" },
          has_street: true,
          streets_count: 22,
          subs: 22,
        },
        {
          osm_id: 64,
          parent_osm_id: 6,
          type: "urban",
          name: { ka: "ვერა", en: "Vera", ru: "Вера" },
          pathway: { ka: "ვერა", en: "Vera", ru: "Вера" },
          seo_title: { ka: "ვერაზე", en: "In Vera", ru: "В Вера" },
          has_street: true,
          streets_count: 52,
          subs: 52,
        },
        {
          osm_id: 65,
          parent_osm_id: 6,
          type: "urban",
          name: { ka: "კრწანისი", en: "Krtsanisi", ru: "Крцаниси" },
          pathway: { ka: "კრწანისი", en: "Krtsanisi", ru: "Крцаниси" },
          seo_title: { ka: "კრწანისში", en: "In Krtsanisi", ru: "В Крцаниси" },
          has_street: true,
          streets_count: 11,
          subs: 11,
        },
        {
          osm_id: 66,
          parent_osm_id: 6,
          type: "urban",
          name: { ka: "მთაწმინდა", en: "Mtatsminda", ru: "Мтацминда" },
          pathway: { ka: "მთაწმინდა", en: "Mtatsminda", ru: "Мтацминда" },
          seo_title: {
            ka: "მთაწმინდაზე",
            en: "In Mtatsminda",
            ru: "В Мтацминда",
          },
          has_street: true,
          streets_count: 76,
          subs: 76,
        },
        {
          osm_id: 67,
          parent_osm_id: 6,
          type: "urban",
          name: { ka: "სოლოლაკი", en: "Sololaki", ru: "Сололаки" },
          pathway: { ka: "სოლოლაკი", en: "Sololaki", ru: "Сололаки" },
          seo_title: { ka: "სოლოლაკში", en: "In Sololaki", ru: "В Сололаки" },
          has_street: true,
          streets_count: 36,
          subs: 36,
        },
      ],
      streets_count: 0,
      subs: 8,
    },
  ],
};
