export const WholePageAd = () => {
  return (
    <svg
      width="380"
      height="350"
      viewBox="0 0 380 350"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g filter="url(#filter0_d_374_2790)">
        <g clipPath="url(#clip0_374_2790)">
          <rect
            x="15"
            y="15"
            width="350"
            height="320"
            rx="10"
            fill="var(--whiteMain)"
          />
          <rect
            x="15"
            y="33"
            width="350"
            height="30"
            fill="var(--whiteHover)"
          />
          <rect
            x="24"
            y="39"
            width="18"
            height="18"
            rx="4"
            fill="var(--main)"
            fillOpacity="0.2"
          />
          <rect
            x="334"
            y="39"
            width="18"
            height="18"
            rx="9"
            fill="var(--main)"
            fillOpacity="0.2"
          />
          <rect
            x="311"
            y="42"
            width="12"
            height="12"
            rx="4"
            fill="var(--skeleton6)"
          />
          <rect
            x="294"
            y="42"
            width="12"
            height="12"
            rx="4"
            fill="var(--skeleton6)"
          />
          <rect
            x="24"
            y="73"
            width="328"
            height="101"
            rx="8"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="24"
            y="184"
            width="328"
            height="54"
            rx="8"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="175.8"
            y="165.8"
            width="3.4"
            height="3.4"
            rx="1.7"
            fill="var(--whiteBgLow)"
            stroke="var(--whiteBgLow)"
            strokeWidth="0.4"
          />
          <rect
            x="183"
            y="166"
            width="3"
            height="3"
            rx="1.5"
            fill="var(--whiteMain)"
          />
          <rect
            x="190"
            y="166"
            width="3"
            height="3"
            rx="1.5"
            fill="var(--whiteMain)"
          />
          <rect
            x="197"
            y="166"
            width="3"
            height="3"
            rx="1.5"
            fill="var(--whiteMain)"
          />
          <rect
            x="33"
            y="206"
            width="309"
            height="11"
            rx="2"
            fill="var(--skeleton6)"
          />
          <rect
            x="33.5"
            y="222.5"
            width="293"
            height="10"
            rx="1.5"
            stroke="var(--skeleton6)"
          />
          <rect
            x="33"
            y="190"
            width="50"
            height="11"
            rx="2"
            fill="var(--main)"
            fillOpacity="0.2"
          />
          <rect
            x="88"
            y="190"
            width="50"
            height="11"
            rx="2"
            fill="var(--main)"
            fillOpacity="0.2"
          />
          <rect
            x="143"
            y="190"
            width="50"
            height="11"
            rx="2"
            fill="var(--main)"
            fillOpacity="0.2"
          />
          <rect
            x="331"
            y="222"
            width="11"
            height="11"
            rx="2"
            fill="var(--main)"
            fillOpacity="0.2"
          />
          <rect
            x="24"
            y="248"
            width="73"
            height="8"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="32"
            y="266"
            width="52"
            height="50"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="36"
            y="269"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="97"
            y="266"
            width="52"
            height="50"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="162"
            y="266"
            width="52"
            height="50"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="227"
            y="266"
            width="52"
            height="50"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="292"
            y="266"
            width="52"
            height="50"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect x="12" y="15" width="360" height="18" fill="var(--main)" />
          <rect
            x="101"
            y="269"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="166"
            y="269"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="231"
            y="269"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="296"
            y="269"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
        </g>
      </g>
      <defs>
        <filter
          id="filter0_d_374_2790"
          x="0"
          y="0"
          width="380"
          height="350"
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          />
          <feOffset />
          <feGaussianBlur stdDeviation="7.5" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
          />
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_374_2790"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_374_2790"
            result="shape"
          />
        </filter>
        <clipPath id="clip0_374_2790">
          <rect
            x="15"
            y="15"
            width="350"
            height="320"
            rx="10"
            fill="var(--whiteMain)"
          />
        </clipPath>
      </defs>
    </svg>
  );
};
export const HomePageAd1 = () => {
  return (
    <svg
      width="380"
      height="350"
      viewBox="0 0 380 350"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g filter="url(#filter0_d_374_2714)">
        <g clipPath="url(#clip0_374_2714)">
          <rect
            x="15"
            y="15"
            width="350"
            height="320"
            rx="10"
            fill="var(--whiteMain)"
          />
          <rect
            x="15"
            y="15"
            width="350"
            height="30"
            fill="var(--whiteHover)"
          />
          <rect
            x="24"
            y="21"
            width="18"
            height="18"
            rx="4"
            fill="var(--main)"
            fillOpacity="0.2"
          />
          <rect
            x="334"
            y="21"
            width="18"
            height="18"
            rx="9"
            fill="var(--main)"
            fillOpacity="0.2"
          />
          <rect
            x="311"
            y="24"
            width="12"
            height="12"
            rx="4"
            fill="var(--skeleton6)"
          />
          <rect
            x="294"
            y="24"
            width="12"
            height="12"
            rx="4"
            fill="var(--skeleton6)"
          />
          <rect
            x="24"
            y="55"
            width="328"
            height="101"
            rx="8"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="24"
            y="166"
            width="328"
            height="54"
            rx="8"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="175.8"
            y="147.8"
            width="3.4"
            height="3.4"
            rx="1.7"
            fill="var(--whiteBgLow)"
            stroke="var(--whiteMain)"
            strokeWidth="0.4"
          />
          <rect
            x="183"
            y="148"
            width="3"
            height="3"
            rx="1.5"
            fill="var(--whiteMain)"
          />
          <rect
            x="190"
            y="148"
            width="3"
            height="3"
            rx="1.5"
            fill="var(--whiteMain)"
          />
          <rect
            x="197"
            y="148"
            width="3"
            height="3"
            rx="1.5"
            fill="var(--whiteMain)"
          />
          <rect
            x="33"
            y="188"
            width="309"
            height="11"
            rx="2"
            fill="var(--skeleton6)"
          />
          <rect
            x="33.5"
            y="204.5"
            width="293"
            height="10"
            rx="1.5"
            stroke="var(--skeleton6)"
          />
          <rect
            x="33"
            y="172"
            width="50"
            height="11"
            rx="2"
            fill="var(--main)"
            fillOpacity="0.2"
          />
          <rect
            x="24"
            y="230"
            width="328"
            height="30"
            rx="4"
            fill="var(--main)"
          />
          <rect
            x="88"
            y="172"
            width="50"
            height="11"
            rx="2"
            fill="var(--main)"
            fillOpacity="0.2"
          />
          <rect
            x="143"
            y="172"
            width="50"
            height="11"
            rx="2"
            fill="var(--main)"
            fillOpacity="0.2"
          />
          <rect
            x="331"
            y="204"
            width="11"
            height="11"
            rx="2"
            fill="var(--main)"
            fillOpacity="0.2"
          />
          <rect
            x="24"
            y="278"
            width="73"
            height="8"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="32"
            y="296"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="97"
            y="296"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="162"
            y="296"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="227"
            y="296"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="292"
            y="296"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="36"
            y="299"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="101"
            y="299"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="166"
            y="299"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="231"
            y="299"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="296"
            y="299"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
        </g>
      </g>
      <defs>
        <filter
          id="filter0_d_374_2714"
          x="0"
          y="0"
          width="380"
          height="350"
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          />
          <feOffset />
          <feGaussianBlur stdDeviation="7.5" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
          />
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_374_2714"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_374_2714"
            result="shape"
          />
        </filter>
        <clipPath id="clip0_374_2714">
          <rect
            x="15"
            y="15"
            width="350"
            height="320"
            rx="10"
            fill="var(--whiteMain)"
          />
        </clipPath>
      </defs>
    </svg>
  );
};
export const HomePageAd2 = () => {
  return (
    <svg
      width="380"
      height="350"
      viewBox="0 0 380 350"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g filter="url(#filter0_d_374_2744)">
        <g clipPath="url(#clip0_374_2744)">
          <rect
            x="15"
            y="15"
            width="350"
            height="320"
            rx="10"
            fill="var(--whiteMain)"
          />
          <rect
            x="15"
            y="15"
            width="350"
            height="30"
            fill="var(--whiteHover)"
          />
          <rect
            x="24"
            y="21"
            width="18"
            height="18"
            rx="4"
            fill="var(--main)"
            fillOpacity="0.2"
          />
          <rect
            x="334"
            y="21"
            width="18"
            height="18"
            rx="9"
            fill="var(--main)"
            fillOpacity="0.2"
          />
          <rect
            x="311"
            y="24"
            width="12"
            height="12"
            rx="4"
            fill="var(--skeleton6)"
          />
          <rect
            x="294"
            y="24"
            width="12"
            height="12"
            rx="4"
            fill="var(--skeleton6)"
          />
          <rect
            x="175.8"
            y="147.8"
            width="3.4"
            height="3.4"
            rx="1.7"
            fill="var(--whiteBgLow)"
            stroke="var(--whiteMain)"
            strokeWidth="0.4"
          />
          <rect
            x="183"
            y="148"
            width="3"
            height="3"
            rx="1.5"
            fill="var(--whiteMain)"
          />
          <rect
            x="190"
            y="148"
            width="3"
            height="3"
            rx="1.5"
            fill="var(--whiteMain)"
          />
          <rect
            x="197"
            y="148"
            width="3"
            height="3"
            rx="1.5"
            fill="var(--whiteMain)"
          />
          <rect
            x="26"
            y="145"
            width="328"
            height="30"
            rx="4"
            fill="var(--main)"
          />
          <rect
            x="30"
            y="61"
            width="73"
            height="8"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="38"
            y="79"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="103"
            y="79"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="168"
            y="79"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="233"
            y="79"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="298"
            y="79"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="42"
            y="82"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="107"
            y="82"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="172"
            y="82"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="237"
            y="82"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="302"
            y="82"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="30"
            y="268"
            width="73"
            height="8"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="38"
            y="286"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="103"
            y="286"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="168"
            y="286"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="233"
            y="286"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="298"
            y="286"
            width="52"
            height="44"
            rx="3"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="42"
            y="289"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="107"
            y="289"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="172"
            y="289"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="237"
            y="289"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="302"
            y="289"
            width="44"
            height="26"
            rx="3"
            fill="var(--skeleton6)"
          />
          <rect
            x="239"
            y="193"
            width="103"
            height="65"
            rx="5"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="38"
            y="203"
            width="103"
            height="10"
            rx="2"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="38"
            y="220"
            width="150"
            height="20"
            rx="2"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="360"
            y="16"
            width="5"
            height="319"
            fill="var(--whiteBgLow)"
          />
          <rect
            x="360"
            y="207"
            width="5"
            height="76"
            fill="var(--main)"
            fillOpacity="0.2"
          />
        </g>
      </g>
      <defs>
        <filter
          id="filter0_d_374_2744"
          x="0"
          y="0"
          width="380"
          height="350"
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          />
          <feOffset />
          <feGaussianBlur stdDeviation="7.5" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
          />
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_374_2744"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_374_2744"
            result="shape"
          />
        </filter>
        <clipPath id="clip0_374_2744">
          <rect
            x="15"
            y="15"
            width="350"
            height="320"
            rx="10"
            fill="var(--whiteMain)"
          />
        </clipPath>
      </defs>
    </svg>
  );
};
export const ProductPageAd1 = () => {
  return (
    <svg
      width="380"
      height="350"
      viewBox="0 0 380 350"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g filter="url(#filter0_d_374_2762)">
        <rect
          x="15"
          y="15"
          width="350"
          height="320"
          rx="10"
          fill="var(--whiteMain)"
        />
        <rect x="15" y="15" width="350" height="30" fill="var(--whiteHover)" />
        <rect
          x="24"
          y="21"
          width="18"
          height="18"
          rx="4"
          fill="var(--main)"
          fillOpacity="0.2"
        />
        <rect
          x="334"
          y="21"
          width="18"
          height="18"
          rx="9"
          fill="var(--main)"
          fillOpacity="0.2"
        />
        <rect
          x="311"
          y="24"
          width="12"
          height="12"
          rx="4"
          fill="var(--skeleton6)"
        />
        <rect
          x="294"
          y="24"
          width="12"
          height="12"
          rx="4"
          fill="var(--skeleton6)"
        />
        <rect x="24" y="62" width="165" height="90" rx="8" fill="var(--main)" />
        <rect
          x="197"
          y="62"
          width="155"
          height="46"
          rx="5"
          fill="var(--whiteBgLow)"
        />
        <rect
          x="24"
          y="161"
          width="220"
          height="85"
          rx="5"
          fill="var(--whiteBgLow)"
        />
        <rect
          x="24"
          y="252"
          width="220"
          height="59"
          rx="5"
          fill="var(--whiteBgLow)"
        />
        <rect
          x="252"
          y="252"
          width="100"
          height="59"
          rx="5"
          fill="var(--whiteBgLow)"
        />
        <rect
          x="252"
          y="161"
          width="100"
          height="85"
          rx="5"
          fill="var(--whiteBgLow)"
        />
        <rect
          x="197"
          y="112"
          width="155"
          height="18"
          rx="5"
          fill="var(--whiteBgLow)"
        />
        <rect
          x="197"
          y="134"
          width="155"
          height="18"
          rx="5"
          fill="var(--whiteBgLow)"
        />
        <rect
          x="94.8"
          y="144.8"
          width="3.4"
          height="3.4"
          rx="1.7"
          fill="var(--whiteMain)"
          stroke="var(--whiteMain)"
          strokeWidth="0.4"
        />
        <rect
          x="101.8"
          y="144.8"
          width="3.4"
          height="3.4"
          rx="1.7"
          fill="var(--main)"
          stroke="var(--whiteMain)"
          strokeWidth="0.4"
        />
        <rect
          x="108.8"
          y="144.8"
          width="3.4"
          height="3.4"
          rx="1.7"
          fill="var(--whiteMain)"
          stroke="var(--whiteMain)"
          strokeWidth="0.4"
        />
        <rect
          x="115.8"
          y="144.8"
          width="3.4"
          height="3.4"
          rx="1.7"
          fill="var(--whiteMain)"
          stroke="var(--whiteMain)"
          strokeWidth="0.4"
        />
      </g>
      <defs>
        <filter
          id="filter0_d_374_2762"
          x="0"
          y="0"
          width="380"
          height="350"
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          />
          <feOffset />
          <feGaussianBlur stdDeviation="7.5" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
          />
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_374_2762"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_374_2762"
            result="shape"
          />
        </filter>
      </defs>
    </svg>
  );
};
export const ProductPageAd2 = () => {
  return (
    <svg
      width="380"
      height="350"
      viewBox="0 0 380 350"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g filter="url(#filter0_d_374_2776)">
        <rect
          x="15"
          y="15"
          width="350"
          height="320"
          rx="10"
          fill="var(--whiteMain)"
        />
        <rect x="15" y="15" width="350" height="30" fill="var(--whiteHover)" />
        <rect
          x="24"
          y="21"
          width="18"
          height="18"
          rx="4"
          fill="var(--main)"
          fillOpacity="0.2"
        />
        <rect
          x="334"
          y="21"
          width="18"
          height="18"
          rx="9"
          fill="var(--main)"
          fillOpacity="0.2"
        />
        <rect
          x="311"
          y="24"
          width="12"
          height="12"
          rx="4"
          fill="var(--skeleton6)"
        />
        <rect
          x="294"
          y="24"
          width="12"
          height="12"
          rx="4"
          fill="var(--skeleton6)"
        />
        <rect
          x="24"
          y="62"
          width="165"
          height="90"
          rx="8"
          fill="var(--whiteBgLow)"
        />
        <rect
          x="197"
          y="62"
          width="155"
          height="46"
          rx="5"
          fill="var(--whiteBgLow)"
        />
        <rect
          x="24"
          y="161"
          width="220"
          height="85"
          rx="5"
          fill="var(--whiteBgLow)"
        />
        <rect
          x="24"
          y="252"
          width="220"
          height="59"
          rx="5"
          fill="var(--whiteBgLow)"
        />
        <rect
          x="252"
          y="252"
          width="100"
          height="59"
          rx="5"
          fill="var(--whiteBgLow)"
        />
        <rect
          x="252"
          y="161"
          width="100"
          height="85"
          rx="5"
          fill="var(--main)"
        />
        <rect
          x="197"
          y="112"
          width="155"
          height="18"
          rx="5"
          fill="var(--whiteBgLow)"
        />
        <rect
          x="197"
          y="134"
          width="155"
          height="18"
          rx="5"
          fill="var(--whiteBgLow)"
        />
        <rect
          x="94.8"
          y="144.8"
          width="3.4"
          height="3.4"
          rx="1.7"
          fill="var(--whiteBgLow)"
          stroke="var(--whiteMain)"
          strokeWidth="0.4"
        />
        <rect
          x="101.8"
          y="144.8"
          width="3.4"
          height="3.4"
          rx="1.7"
          fill="var(--whiteMain)"
          stroke="var(--whiteMain)"
          strokeWidth="0.4"
        />
        <rect
          x="108.8"
          y="144.8"
          width="3.4"
          height="3.4"
          rx="1.7"
          fill="var(--whiteMain)"
          stroke="var(--whiteMain)"
          strokeWidth="0.4"
        />
        <rect
          x="115.8"
          y="144.8"
          width="3.4"
          height="3.4"
          rx="1.7"
          fill="var(--whiteMain)"
          stroke="var(--whiteMain)"
          strokeWidth="0.4"
        />
      </g>
      <defs>
        <filter
          id="filter0_d_374_2776"
          x="0"
          y="0"
          width="380"
          height="350"
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          />
          <feOffset />
          <feGaussianBlur stdDeviation="7.5" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
          />
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_374_2776"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_374_2776"
            result="shape"
          />
        </filter>
      </defs>
    </svg>
  );
};
